# Generated by Django 5.2.15 on 2026-06-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no2', models.FloatField(verbose_name='NO₂ (ppm)')),
                ('co', models.FloatField(verbose_name='CO (ppm)')),
                ('pm10', models.FloatField(verbose_name='PM₁₀ (µg/m³)')),
                ('pm25', models.FloatField(verbose_name='PM₂.₅ (µg/m³)')),
                ('predicted_class', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('probabilities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
